### ISSUE TITLE
Clicking a link build with the `{{link}}` helper, the transition is not executed in Edge <= 18

### ISSUE THREAD

**Issue by dcyriller** [buschtoens/ember-link#459]
Hi there 👋,

Thanks for this addon, that we use. :)
I think I found a bug. AFAICT the issue would be in ember-source. But I'm opening the issue here for tracking purpose.

## A bug

Clicking a link build with the `{{link}}` helper, the transition is not executed in Edge <= 18.

Instead, I get the following error in the console:
`Unable to get property 'router' of undefined or null reference`
on the following line:
https://github.com/buschtoens/ember-link/blob/8f0fab3428b9a06d9e61f3ecf75286d68f2e40b0/addon/link.ts#L227

## A possible cause

The bug only happens in Edge <= 18. I wonder if the code: https://github.com/buschtoens/ember-link/blob/8f0fab3428b9a06d9e61f3ecf75286d68f2e40b0/addon/link.ts#L276-L283 would not be a reproduction for this issue in the framework: https://github.com/emberjs/ember.js/issues/18955

**Comment by buschtoens** [comment]
Great detective work! 🕵️

I think you found the correct root cause. You could try replacing `super` with something like the following, to test your theory:

```ts
return Link.prototype.transitionTo.call(this);
```

**Comment by dcyriller** [comment]
> Great detective work! 

😆 it was indeed detective work.

Thanks for the pointer... It did not work as is but gave me the idea to inline Link's `transitionTo` into UILink... And the bug is indeed fixed when removing `super`. I'm going to report the details of my investigation in the cross-linked issue.

What would be the best way forward regarding the bug in ember-link? Do you prefer to wait for the root cause to be fixed? Or do you wish to inline Link's `transitionTo` into UILink?

**Comment by buschtoens** [comment]
Ah yes, that didn't work because `@action` actually replaces the original `prototype` value with a getter: https://github.com/emberjs/ember.js/blob/master/packages/%40ember/object/index.js#L120-L152

Because the `@action` decorator stashes the real function away into a private `BINDINGS_MAP`, we also cannot conveniently access it again, to apply a monkey-patch fix. :(

As Edge <= 18 isn't really in the support matrix of this addon, I'd ideally like to wait for an upstream fix, but I'd also like to unblock you.

Can you maybe answer the questions from https://github.com/emberjs/ember.js/issues/18955#issuecomment-626096291 ?

> Hmm, this is pretty odd. Some questions:
> 
> * What are you `config/targets.js`?
> * Is this the same in dev vs prod builds?
> * Can you share the transpiled output of both files?
